TEST

diff --git a/.github/workflows/pipelineC.yml b/.github/workflows/pipelineC.yml
--- a/.github/workflows/pipelineC.yml
+++ b/.github/workflows/pipelineC.yml
@@ -1,4 +1,4 @@
-name: Workflow
+name: SonarCloud Integration
 
 on:
   push:
@@ -6,7 +6,7 @@ on:
       - feat-devsecops
 
 jobs:
-  SAST:
+  analyze:
     runs-on: ubuntu-latest
     steps:
       - name: Set up JDK 17
@@ -18,7 +18,7 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v2
 
-      - name: Validating project existence on SonarCloud
+      - name: Validate project existence on SonarCloud
         id: ValidateProjectSonar
         env:
           SONAR_TOKEN: "${{ secrets.SONAR_TOKEN }}"
@@ -26,28 +26,41 @@ jobs:
           set +e
 
           # Verificar si el proyecto ya existe en SonarCloud
-          curl -f -X GET -u "${{ secrets.SONAR_TOKEN }}:" 'https://sonarcloud.io/api/projects/search?organization=devseco&projects=Laboratorio-final' \
-            | grep -q '"name":"Laboratorio-final"'
+          response=$(curl -s -f -X GET -u "${{ secrets.SONAR_TOKEN }}:" 'https://sonarcloud.io/api/projects/search?organization=devseco&projects=Laboratorio-final')
 
-          if [ $? -eq 0 ]; then
+          if echo "$response" | grep -q '"name":"Laboratorio-final"'; then
             echo "Project cristinamatheuv/Laboratorio-final already exists on SonarCloud"
           else
             echo "Project cristinamatheuv/Laboratorio-final does not exist on SonarCloud, creating..."
 
             # Crear el proyecto en SonarCloud
-            curl -f -X POST -u "${{ secrets.SONAR_TOKEN }}:" 'https://sonarcloud.io/api/projects/create' \
+            create_project_response=$(curl -s -f -X POST -u "${{ secrets.SONAR_TOKEN }}:" 'https://sonarcloud.io/api/projects/create' \
               -d "name=Laboratorio-final" \
-              -d "projects=Laboratorio-final" \
               -d "organization=devseco" \
-              -d "visibility=public"
+              -d "visibility=public")
+
+            if echo "$create_project_response" | grep -q '"errors"'; then
+              echo "Failed to create project on SonarCloud"
+              exit 1
+            fi
 
             echo "Project cristinamatheuv/Laboratorio-final created successfully on SonarCloud"
           fi
 
-          # Renombrar la rama principal del proyecto si se creó
-          if [ $? -eq 0 ]; then
-            echo "Setting 'main' as the default branch"
-            curl -X POST -u "${{ secrets.SONAR_TOKEN }}:" 'https://sonarcloud.io/api/project_branches/rename' \
-              -d "name=main" \
-              -d "project=Laboratorio-final"
+          # Renombrar la rama principal del proyecto si se creó correctamente
+          echo "Setting 'main' as the default branch"
+          rename_branch_response=$(curl -s -f -X POST -u "${{ secrets.SONAR_TOKEN }}:" 'https://sonarcloud.io/api/project_branches/rename' \
+            -d "name=main" \
+            -d "project=Laboratorio-final")
+
+          if echo "$rename_branch_response" | grep -q '"errors"'; then
+            echo "Failed to rename main branch on SonarCloud"
+            exit 1
           fi
+
+          echo "Main branch renamed successfully on SonarCloud"
+
+      - name: SonarCloud Scan
+        env:
+          SONAR_TOKEN: "${{ secrets.SONAR_TOKEN }}"
+        run: sonar-scanner
